### ISSUE TITLE
Can this plugin be used to setup APM & Insights tracking with New Relic?

### ISSUE THREAD

**Issue by jpvajda** [porchdotcom/gatsby-source-newrelic-apps#1]
Hello,

This is a question that I had, as the readme didn't have a lot of information about the use of this plugin, so I thought I'd file an issue to clarify. Can this be used to send data to new relic to tracking APM and insights data for a Gatsby Application? 

Thank you for taking the time to answer my question.

**Comment by AP-Porch** [comment]
Hi @jpvajda 

The intent of this plugin was just to be able to expose your New Relic applications as Gatsby nodes. It does not help with getting your gatsby app into NewRelic APM or Insights.

**Comment by jpvajda** [comment]
@AP-Porch Thank you for the quick response!
